services:
  backend:
    build: ./backend
    ports:
      - "8999:8999"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: user
      DB_PASSWORD: mypassword
      DB_NAME: chitchat
      DB_PORT: 5432
    tty: true
  
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: chitchat
      POSTGRES_USER: user
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5555:5432"
    volumes:
      - db-store:/var/lib/postgresql/data
      - ./backend/data/setup.sql:/setup.sql
      - ./backend/data/setup.sh:/docker-entrypoint-initdb.d/setup.sh
volumes:
  db-store: